### ISSUE TITLE
function yaml should accept any valid k8s env config

### ISSUE THREAD

**Issue by markfisher** [markfisher/sk8s#130]
currently we only expose "name" and "value" for the env section of a function yaml, but we should allow "valueFrom" (including support for secrets) such as:

```
env:
- name: DB_PASSWORD
  valueFrom:
    secretKeyRef:
      name: db
      key: db-password
```
